# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [prereleased]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to testpypi
    runs-on: ubuntu-latest
    environment:
      name: prerelease
      url: https://testpypi.org/p/ghatesting-so
    permissions:
      id-token: write
    steps:
    - name: Get sdist artefacts
      uses: actions/download-artifact@v5
      with:
        name: python-package
        path: dist
        
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/
